#![allow(non_upper_case_globals)]
#![allow(clippy::arc_with_non_send_sync)]

// Modules (Keep relevant ones, remove GTK-specific ones later)
mod alpm_helper;
//mod application_browser; // Needs heavy refactoring for QML/Model
mod config; // Generated by build.rs now
mod embed_data; // May be replaced by Qt resources
// mod gresource; // GTK resource system, remove
mod installer;
mod kwin_dbus;
mod localization;
mod logger;
// mod pages; // Logic needs to move to AppModel/QML
mod systemd_units;
mod utils;
// mod window; // GTK window, remove

use config::*;
use utils::*;

use std::path::Path;
use std::str;
use std::sync::{Arc, Mutex};

use i18n_embed::DesktopLanguageRequester;
use once_cell::sync::Lazy;
use serde_json::json;
use tracing::{debug, error};
use unic_langid::LanguageIdentifier;

const RESPREFIX: &str = "/org/cachyos/hello";

// QMetaObject integration
use qmetaobject::prelude::*;

static G_SAVE_JSON: Lazy<Mutex<serde_json::Value>> = Lazy::new(|| {
    let preferences = get_preferences();
    let saved_json = get_saved_json(&preferences);
    Mutex::new(saved_json)
});

fn get_saved_locale() -> Option<String> {
    let saved_json = &*G_SAVE_JSON.lock().unwrap();
    Some(saved_json["locale"].as_str()?.to_owned())
}

fn get_saved_json(preferences: &serde_json::Value) -> serde_json::Value {
    let save_path = fix_path(preferences["save_path"].as_str().unwrap());
    if !Path::new(&save_path).exists() {
        json!({"locale": ""})
    } else {
        read_json(save_path.as_str())
    }
}

fn get_preferences() -> serde_json::Value {
    let pref_file = crate::embed_data::get("preferences.json").unwrap();
    let pref = std::str::from_utf8(pref_file.data.as_ref()).unwrap();
    serde_json::from_str(pref).expect("Unable to parse")
}

qrc!(register_resources,
    "ui" as "qml" {
        "main.qml",
        "InfoPage.qml",
        "IconButton.qml",
        "MainPageButtons.qml",
        "MainPageControls.qml",
        "HomePage.qml",
    },
);

// --- QObject Model Definition ---
#[derive(Default, QObject)]
pub struct AppModel {
    base: qt_base_class!(trait QObject),

    // Signals
    navigate: qt_signal!(page: String, title: String, content: String),

    // Invokable Methods
    setLocale: qt_method!(fn(&mut self, locale_id: String)),
    toggleAutostart: qt_method!(fn(&mut self)),
    showPage: qt_method!(fn(&mut self, page_id: String)),
    openLink: qt_method!(fn(&self, url: String)),
    launchInstaller: qt_method!(fn(&self)),
    showAbout: qt_method!(fn(&self)), // Implement an about dialog/page
    // Add methods for App/Tweak/DNS actions
}

impl AppModel {
    fn setLocale(&mut self, locale_id: String) {}
    fn toggleAutostart(&mut self) {}
    fn showPage(&mut self, page_id: String) {}
    fn openLink(&self, url: String) {
        tracing::debug!("open link {url}");
    }
    fn launchInstaller(&self) {}
    fn showAbout(&self) {}
}

// Implement methods for AppModel
impl AppModel {
    // Helper to get translated string
    fn fl(&self, message_id: &str) -> String {
        crate::localization::get_locale_text(utils::get_translation_msgid(message_id))
            /*
        self.fluent_loader.lookup(&Translations, message_id, None)
            .unwrap_or_else(|| {
                error!("Missing translation for: {}", message_id);
                format!("MISSING: {}", message_id)
            })
*/
    }

    // Update all QProperty members with current translations
    fn update_translations(&mut self) {
            /*
        self.windowTitle.set(self.fl("app-title").into());
        self.welcomeTitle.set(self.fl("welcome-title").into());
        self.welcomeMessage.set(self.fl("welcome-message").into());
        self.documentationHeading.set(self.fl("documentation-heading").into());
        self.readmeButton.set(self.fl("readme-button").into());
        self.releaseButton.set(self.fl("release-button").into());
        self.wikiButton.set(self.fl("wiki-button").into());
        self.supportHeading.set(self.fl("support-heading").into());
        self.forumButton.set(self.fl("forum-button").into());
        self.softwareButton.set(self.fl("software-button").into());
        self.installationHeading.set(self.fl("installation-heading").into());
        self.launchInstallerButton.set(self.fl("launch-installer-button").into());
        self.projectHeading.set(self.fl("project-heading").into());
        self.involvedButton.set(self.fl("involved-button").into());
        self.developmentButton.set(self.fl("development-button").into());
        self.donateButton.set(self.fl("donate-button").into());
        self.launchAtStartLabel.set(self.fl("launch-at-start-label").into());
        self.aboutButtonTooltip.set(self.fl("about-button-tooltip").into());
        self.webResourceTooltip.set(self.fl("web-resource-tooltip").into());
        self.aboutActionText.set(self.fl("about-action-text").into());
        // Update other translatable properties...
*/
    }

    // Update the model for the language ComboBox
    fn update_locale_model(&mut self) {
            /*
        let mut locales = QVariantList::new();
        if let Ok(available) = self.fluent_loader.available_languages(&Translations) {
            for lang_id in available {
                let mut map = QVariantMap::new();
                // Get language name (requires mapping logic or fluent resource)
                let lang_name = localization::get_language_name(&lang_id).unwrap_or_else(|| lang_id.to_string());
                map.insert("id".into(), QVariant::from(QString::from(lang_id.to_string())));
                map.insert("name".into(), QVariant::from(QString::from(lang_name)));
                locales.push(QVariant::from(map));
            }
        }
        self.localeModel.set(locales);
*/
    }
}

// --- Main Application Logic ---
fn main() -> anyhow::Result<()> {
    qmetaobject::log::init_qt_to_rust();

    let _ = logger::setup_logger();
    debug!("Starting CachyOS Hello Qt Version");

    register_resources();

    //qmetaobject::log::init_qt_to_tracing();

    // Create and register the Rust model
    let model = QObjectBox::new(AppModel::default());

    // Initialize QML Engine
    let mut engine = QmlEngine::new();

    // Expose the model to QML
    engine.set_object_property("rustModel".into(), model.pinned());

    engine.set_property("windowTitle".into(), QString::from(fl!("welcome-title")).into());
    engine.set_property("welcomeTitle".into(), QString::from(fl!("welcome-title")).into());
    engine.set_property("welcomeMessage".into(), QString::from(fl!("welcome-body")).into());
    engine.set_property("documentationHeading".into(), QString::from(fl!("section-docs")).into());
    engine.set_property("readmeButton".into(), QString::from(fl!("button-readme-label")).into());
    engine.set_property("releaseButton".into(), QString::from(fl!("button-release-info-label")).into());
    engine.set_property("wikiButton".into(), QString::from(fl!("button-wiki-label")).into());
    engine.set_property("supportHeading".into(), QString::from(fl!("section-support")).into());
    engine.set_property("forumButton".into(), QString::from(fl!("button-forum-label")).into());
    engine.set_property("softwareButton".into(), QString::from(fl!("button-software-label")).into());
    engine.set_property("installationHeading".into(), QString::from(fl!("section-installer")).into());
    engine.set_property("launchInstallerButton".into(), QString::from(fl!("button-installer-label")).into());
    engine.set_property("projectHeading".into(), QString::from(fl!("section-project")).into());
    engine.set_property("involvedButton".into(), QString::from(fl!("button-involved-label")).into());
    engine.set_property("developmentButton".into(), QString::from(fl!("button-development-label")).into());
    engine.set_property("donateButton".into(), QString::from(fl!("button-donate-label")).into());
    engine.set_property("launchAtStartLabel".into(), QString::from(fl!("launch-start-label")).into());
    engine.set_property("aboutButtonTooltip".into(), QString::from(fl!("button-about-tooltip")).into());
    engine.set_property("webResourceTooltip".into(), QString::from(fl!("button-web-resource-tooltip")).into());
    engine.set_property("aboutActionText".into(), QString::from(fl!("about-dialog-title")).into());

    engine.set_property("forumUrl".into(), QString::from("https://discuss.cachyos.org").into());

    // Load the main QML file from Qt resources
    engine.load_file("qrc:/qml/main.qml".into());
    engine.exec();
/*
    // Run the Qt Application event loop
    let app = QGuiApplication::new();
    match app {
        Some(app) => {
            app.exec();
            /*
            // Save state on exit?
            let final_state = G_SAVE_JSON.lock().unwrap();
            let prefs = load_preferences().unwrap_or_default(); // Reload prefs just in case
            if let Err(e) = write_saved_json(&prefs, &final_state) {
                error!("Failed to save final state: {}", e);
            }
            debug!("Exiting CachyOS Hello");
            ExitCode::SUCCESS*/
        }
        None => {
            anyhow::bail!("Failed to create QGuiApplication");
        }
    }*/
    Ok(())
}

            /*
// --- Helper Functions (Adapted from old main/utils) ---

fn load_preferences() -> Result<Value, anyhow::Error> {
    // Try system path first, then fallback to user path or internal default
    let sys_path = "/etc/cachyos-hello/cachyos-hello.json";
    let user_path = "~/.config/cachyos-hello/cachyos-hello.json"; // Needs expansion
    let share_path = "/usr/share/cachyos-hello/cachyos-hello.json"; // Build system should install here?

    let path_to_try = if Path::new(sys_path).exists() {
        sys_path.to_string()
    } else if Path::new(share_path).exists() {
        share_path.to_string()
    } else {
        utils::fix_path(user_path) // Expand ~
    };

    debug!("Loading preferences from: {}", path_to_try);
    let mut f = File::open(path_to_try)?;
    let mut buffer = String::new();
    f.read_to_string(&mut buffer)?;
    let prefs: Value = serde_json::from_str(&buffer)?;
    Ok(prefs)
}

fn load_saved_json(preferences: &Value) -> Value {
    let save_path = utils::fix_path(preferences["save_path"].as_str().unwrap_or(""));
    if save_path.is_empty() {
        return json!({ "locale": "" });
    }
    match File::open(&save_path) {
        Ok(mut f) => {
            let mut buffer = String::new();
            if f.read_to_string(&mut buffer).is_ok() {
                match serde_json::from_str(&buffer) {
                    Ok(json) => json,
                    Err(_) => {
                        error!("Failed to parse saved state file: {}", save_path);
                        json!({ "locale": "" })
                    }
                }
            } else {
                error!("Failed to read saved state file: {}", save_path);
                json!({ "locale": "" })
            }
        }
        Err(_) => {
            // File doesn't exist, return default
            debug!("Saved state file not found: {}", save_path);
            json!({ "locale": "" })
        }
    }
}

fn write_saved_json(preferences: &Value, state: &Value) -> Result<(), anyhow::Error> {
    let save_path = utils::fix_path(preferences["save_path"].as_str().unwrap_or(""));
    if save_path.is_empty() {
        return Err(anyhow::anyhow!("Save path is empty in preferences"));
    }
    let save_dir = Path::new(&save_path).parent().ok_or_else(|| anyhow::anyhow!("Invalid save path"))?;
    fs::create_dir_all(save_dir)?;
    let mut f = File::create(&save_path)?;
    let buffer = serde_json::to_string_pretty(state)?;
    f.write_all(buffer.as_bytes())?;
    debug!("Saved state to: {}", save_path);
    Ok(())
}

// Adapt set_autostart from window.rs or utils.rs
fn set_autostart_state(enable: bool, preferences: &Value) -> Result<(), anyhow::Error> {
    let autostart_path = utils::fix_path(preferences["autostart_path"].as_str().unwrap_or(""));
    let desktop_path = preferences["desktop_path"].as_str().unwrap_or("");

    if autostart_path.is_empty() || desktop_path.is_empty() {
        return Err(anyhow::anyhow!("Autostart paths not configured"));
    }

    let config_dir = Path::new(&autostart_path)
        .parent()
        .ok_or_else(|| anyhow::anyhow!("Invalid autostart path"))?;
    fs::create_dir_all(config_dir)?;

    let exists = Path::new(&autostart_path).exists();

    if enable && !exists {
        // Create symlink
        #[cfg(unix)]
        std::os::unix::fs::symlink(desktop_path, &autostart_path)?;
        #[cfg(not(unix))]
        return Err(anyhow::anyhow!("Autostart via symlink not supported on this OS"));
        debug!("Created autostart link: {}", autostart_path);
    } else if !enable && exists {
        // Remove file/symlink
        fs::remove_file(&autostart_path)?;
        debug!("Removed autostart link: {}", autostart_path);
    }
    Ok(())
}

// Stub for reading page content - replace with actual resource reading
fn read_page_content(locale: &LanguageIdentifier, page_id: &str) -> String {
    let path = format!("pages/{}/{}.md", locale, page_id);
    let fallback_path = format!("pages/en/{}.md", page_id);

    // Use rust-embed or Qt resource system to read the content
    // Example using rust-embed (assuming embedded files)
    /*
    match crate::embed_data::HelloData::get(&path) {
        Some(file) => std::str::from_utf8(file.data.as_ref()).unwrap_or("").to_string(),
        None => match crate::embed_data::HelloData::get(&fallback_path) {
            Some(file) => std::str::from_utf8(file.data.as_ref()).unwrap_or("").to_string(),
            None => format!("Error: Page '{}' not found.", page_id),
        }
    }
    */
    // Placeholder:
    format!("Content for page '{}' (locale: {}). Path: qrc:/{}", page_id, locale, path)
}
*/
